name: Lindsay.Reich
favicon: null
layout_spectrum: 0.89655
typography_spectrum: 0.48171
title: Living Art
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#0b0b0b'
    - '#65717d'
    - '#9fa8a5'
    - '#50442e'
  brandStrength: 0.875
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 1
purpose: []
